export default {
  products: [
    {
      _id: '111111111111111111111111',
      name: 'Nike Full Zip Running shirts',
      category: 'Shirts',
      image: '/images/product_1.jpg',
      price: '200',
      brand: 'Nike',
      rating: 4.5,
      numberReviews: 10,
      countInStock: 8,
    },
    {
      _id: '222222222222222222222222',
      name: 'Puma Running shorts',
      category: 'Pants',
      image: '/images/product_2.jpg',
      price: '500',
      brand: 'Puma',
      rating: 5,
      numberReviews: 40,
      countInStock: 5,
    },
    {
      _id: '3',
      name: 'Uzzi Baseball Cap',
      category: 'Hats',
      image: '/images/product_3.jpg',
      price: '150',
      brand: 'Uzzi',
      rating: 3,
      numberReviews: 20,
      countInStock: 11,
    },
    {
      _id: '4',
      name: 'Under Armour Hoodie',
      category: 'Shirts',
      image: '/images/product_4.jpg',
      price: '450',
      brand: 'Under Armour',
      rating: 5,
      numberReviews: 5,
      countInStock: 0,
    },
    {
      _id: '5',
      name: 'Adidas Sweat Pants',
      category: 'Pants',
      image: '/images/product_5.jpg',
      price: '500',
      brand: 'Nike',
      rating: 3,
      numberReviews: 55,
      countInStock: 5,
    },
    {
      _id: '6',
      name: 'Umbro Running shirt',
      category: 'Shirts',
      image: '/images/product_6.jpg',
      price: '250',
      brand: 'Umbro',
      rating: 4,
      numberReviews: 33,
      countInStock: 6,
    },
  ],
};
